### ISSUE TITLE
dist script will dirty the build

### ISSUE THREAD

**Issue by aggie05engineer** [palantir/distgo#142]
When using godel's dist command/plugin (which calls into distgo) we hit an issue if using a dist script. The build is marked `dirty` even if it isn't which can lead to artifacts being missed and therefore a failed build.

Example:

        test-app:
          type: manual
          config:
            extension: tgz
          script: |
            #!/bin/bash
            set -euo pipefail
            # jump out of yaml to the dist-script
            ${PROJECT_DIR}/dist-scripts/dist.sh

Our `dist.sh` uses godel's `godelw project-version` which is the version used for the artifact existence check.

The problem is that distgo writes a script file _inside_ the `PROJECT_DIR` which dirties the git workspace. See https://github.com/palantir/distgo/blob/master/distgo/script.go#L30. This script should be written to a build directory to avoid dirtying the workspace and messing with the version.

The issue is particularly nasty to chase down as the workspace is clean when inspecting what is dirty. The reason for _that_ is the script file is cleaned up after use and disappears by the time an engineer can look at what went wrong.

**Comment by bluekeyes** [comment]
I don't have an opinion on whether Godel should use the project directory for these temporary files, but I do think it's unusual for a dist script to invoke Godel, which is how this is dirty state becomes visible.

Is there a reason the `VERSION` variable added to the [dist script environment](https://github.com/palantir/distgo/blob/master/distgo/env.go#L58) doesn't work here and you need to call `./godelw project-version` instead?

**Comment by nmiyake** [comment]
The suggestion made by @bluekeyes is the proper way to handle this -- closing out.
